/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.chromatics.ChromaticProfile', null, global);
goog.exportSymbol('proto.chromatics.ChromaticProfile.HSLP', null, global);
goog.exportSymbol('proto.chromatics.Image', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chromatics.Image = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chromatics.Image, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chromatics.Image.displayName = 'proto.chromatics.Image';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chromatics.ChromaticProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.chromatics.ChromaticProfile.repeatedFields_, null);
};
goog.inherits(proto.chromatics.ChromaticProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chromatics.ChromaticProfile.displayName = 'proto.chromatics.ChromaticProfile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chromatics.ChromaticProfile.HSLP = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chromatics.ChromaticProfile.HSLP, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chromatics.ChromaticProfile.HSLP.displayName = 'proto.chromatics.ChromaticProfile.HSLP';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chromatics.Image.prototype.toObject = function(opt_includeInstance) {
  return proto.chromatics.Image.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chromatics.Image} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chromatics.Image.toObject = function(includeInstance, msg) {
  var f, obj = {
    b64: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chromatics.Image}
 */
proto.chromatics.Image.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chromatics.Image;
  return proto.chromatics.Image.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chromatics.Image} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chromatics.Image}
 */
proto.chromatics.Image.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setB64(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chromatics.Image.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chromatics.Image.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chromatics.Image} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chromatics.Image.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getB64();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string b64 = 1;
 * @return {string}
 */
proto.chromatics.Image.prototype.getB64 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.chromatics.Image.prototype.setB64 = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.chromatics.ChromaticProfile.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chromatics.ChromaticProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.chromatics.ChromaticProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chromatics.ChromaticProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chromatics.ChromaticProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    hslpList: jspb.Message.toObjectList(msg.getHslpList(),
    proto.chromatics.ChromaticProfile.HSLP.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chromatics.ChromaticProfile}
 */
proto.chromatics.ChromaticProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chromatics.ChromaticProfile;
  return proto.chromatics.ChromaticProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chromatics.ChromaticProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chromatics.ChromaticProfile}
 */
proto.chromatics.ChromaticProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.chromatics.ChromaticProfile.HSLP;
      reader.readMessage(value,proto.chromatics.ChromaticProfile.HSLP.deserializeBinaryFromReader);
      msg.addHslp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chromatics.ChromaticProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chromatics.ChromaticProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chromatics.ChromaticProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chromatics.ChromaticProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHslpList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.chromatics.ChromaticProfile.HSLP.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chromatics.ChromaticProfile.HSLP.prototype.toObject = function(opt_includeInstance) {
  return proto.chromatics.ChromaticProfile.HSLP.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chromatics.ChromaticProfile.HSLP} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chromatics.ChromaticProfile.HSLP.toObject = function(includeInstance, msg) {
  var f, obj = {
    h: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
    s: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    l: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    p: +jspb.Message.getFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chromatics.ChromaticProfile.HSLP}
 */
proto.chromatics.ChromaticProfile.HSLP.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chromatics.ChromaticProfile.HSLP;
  return proto.chromatics.ChromaticProfile.HSLP.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chromatics.ChromaticProfile.HSLP} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chromatics.ChromaticProfile.HSLP}
 */
proto.chromatics.ChromaticProfile.HSLP.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setH(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setS(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setL(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setP(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chromatics.ChromaticProfile.HSLP.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chromatics.ChromaticProfile.HSLP.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chromatics.ChromaticProfile.HSLP} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chromatics.ChromaticProfile.HSLP.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getH();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getS();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getL();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getP();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional float h = 1;
 * @return {number}
 */
proto.chromatics.ChromaticProfile.HSLP.prototype.getH = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.chromatics.ChromaticProfile.HSLP.prototype.setH = function(value) {
  jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float s = 2;
 * @return {number}
 */
proto.chromatics.ChromaticProfile.HSLP.prototype.getS = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.chromatics.ChromaticProfile.HSLP.prototype.setS = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float l = 3;
 * @return {number}
 */
proto.chromatics.ChromaticProfile.HSLP.prototype.getL = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.chromatics.ChromaticProfile.HSLP.prototype.setL = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float p = 4;
 * @return {number}
 */
proto.chromatics.ChromaticProfile.HSLP.prototype.getP = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.chromatics.ChromaticProfile.HSLP.prototype.setP = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * repeated HSLP hslp = 1;
 * @return {!Array<!proto.chromatics.ChromaticProfile.HSLP>}
 */
proto.chromatics.ChromaticProfile.prototype.getHslpList = function() {
  return /** @type{!Array<!proto.chromatics.ChromaticProfile.HSLP>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.chromatics.ChromaticProfile.HSLP, 1));
};


/** @param {!Array<!proto.chromatics.ChromaticProfile.HSLP>} value */
proto.chromatics.ChromaticProfile.prototype.setHslpList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.chromatics.ChromaticProfile.HSLP=} opt_value
 * @param {number=} opt_index
 * @return {!proto.chromatics.ChromaticProfile.HSLP}
 */
proto.chromatics.ChromaticProfile.prototype.addHslp = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.chromatics.ChromaticProfile.HSLP, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.chromatics.ChromaticProfile.prototype.clearHslpList = function() {
  this.setHslpList([]);
};


goog.object.extend(exports, proto.chromatics);
