# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chromatics_pb2 as chromatics__pb2


class ProfilerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetChromaticProfile = channel.unary_unary(
        '/chromatics.Profiler/GetChromaticProfile',
        request_serializer=chromatics__pb2.Image.SerializeToString,
        response_deserializer=chromatics__pb2.ChromaticProfile.FromString,
        )


class ProfilerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetChromaticProfile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProfilerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetChromaticProfile': grpc.unary_unary_rpc_method_handler(
          servicer.GetChromaticProfile,
          request_deserializer=chromatics__pb2.Image.FromString,
          response_serializer=chromatics__pb2.ChromaticProfile.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chromatics.Profiler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
